repos:

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
      - id: detect-secrets
        name: detect secrets
        args: [ '--baseline', '.secrets.baseline' ]
        exclude: yarn.lock

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
#      - id: check-added-large-files
#      - id: check-json
#      - id: check-yaml
#      - id: detect-aws-credentials
      - id: detect-private-key
      - id: no-commit-to-branch
        args: [ --branch, main, --branch, master, --pattern, release/.* ]

  - repo: local
    hooks:
      - id: yarn-lint
        name: yarn lint
        entry: npx yarn lint
        language: system
        pass_filenames: false

# Portal v1 enter into maintenance mode -- dependencies outdated/audit are handled manually on case by case basis
#  - repo: local
#    hooks:
#      - id: yarn-audit
#        name: yarn audit
#        entry: npx yarn audit --groups dependencies
#        language: system
#        pass_filenames: false

# Hitting a bit too wide
#  - repo: https://github.com/pre-commit/mirrors-prettier
#    rev: v2.5.1
#    hooks:
#      - id: prettier
