version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
#      python: 3.9
    commands:
#      - pip install detect-secrets pre-commit
      - yarn install
  build:
    commands:
#      - yarn run precommit
      - |
        REACT_APP_STAGE=$STAGE \
        REACT_APP_REGION=$REGION \
        REACT_APP_API_URL=$API_URL \
        REACT_APP_HTSGET_URL=$HTSGET_URL \
        REACT_APP_COG_USER_POOL_ID=$COGNITO_USER_POOL_ID \
        REACT_APP_COG_IDENTITY_POOL_ID=$COGNITO_IDENTITY_POOL_ID \
        REACT_APP_COG_APP_CLIENT_ID_STAGE=$COGNITO_APP_CLIENT_ID_STAGE \
        REACT_APP_OAUTH_DOMAIN=$OAUTH_DOMAIN \
        REACT_APP_OAUTH_REDIRECT_IN_STAGE=$OAUTH_REDIRECT_IN_STAGE \
        REACT_APP_OAUTH_REDIRECT_OUT_STAGE=$OAUTH_REDIRECT_OUT_STAGE \
        REACT_APP_UNSPLASH_CLIENT_ID=$UNSPLASH_CLIENT_ID \
        yarn build
      - aws s3 sync build/ $S3
