version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - npm install
  build:
    commands:
      - REACT_APP_STAGE=$STAGE npm run build
      - aws s3 sync build/ $S3
