version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - npm install
  build:
    commands:
      - |
        REACT_APP_STAGE=$STAGE \
        REACT_APP_REGION=$REGION \
        REACT_APP_API_ID=$API_ID \
        REACT_APP_COG_USER_POOL_ID=$COGNITO_USER_POOL_ID \
        REACT_APP_COG_IDENTITY_POOL_ID=$COGNITO_IDENTITY_POOL_ID \
        REACT_APP_COG_APP_CLIENT_ID_STAGE=$COGNITO_APP_CLIENT_ID_STAGE \
        REACT_APP_COG_APP_CLIENT_ID_LOCAL=$COGNITO_APP_CLIENT_ID_LOCAL \
        REACT_APP_OAUTH_DOMAIN=$OAUTH_DOMAIN \
        REACT_APP_OAUTH_REDIRECT_IN_STAGE=$OAUTH_REDIRECT_IN_STAGE \
        REACT_APP_OAUTH_REDIRECT_OUT_STAGE=$OAUTH_REDIRECT_OUT_STAGE \
        REACT_APP_OAUTH_REDIRECT_IN_LOCAL=$OAUTH_REDIRECT_IN_LOCAL \
        REACT_APP_OAUTH_REDIRECT_OUT_LOCAL=$OAUTH_REDIRECT_OUT_LOCAL \
        npm run build
      - aws s3 sync build/ $S3
