version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - yarn install
  build:
    commands:
      - |
        VITE_STAGE=$STAGE \
        VITE_REGION=$REGION \
        VITE_API_URL=$API_URL \
        VITE_HTSGET_URL=$HTSGET_URL \
        VITE_GPL_SUBMIT_JOB=$GPL_SUBMIT_JOB \
        VITE_GPL_SUBMIT_JOB_MANUAL=$GPL_SUBMIT_JOB_MANUAL \
        VITE_GPL_CREATE_LINX_PLOT=$GPL_CREATE_LINX_PLOT \
        VITE_COG_USER_POOL_ID=$COGNITO_USER_POOL_ID \
        VITE_COG_IDENTITY_POOL_ID=$COGNITO_IDENTITY_POOL_ID \
        VITE_COG_APP_CLIENT_ID_STAGE=$COGNITO_APP_CLIENT_ID_STAGE \
        VITE_OAUTH_DOMAIN=$OAUTH_DOMAIN \
        VITE_OAUTH_REDIRECT_IN_STAGE=$OAUTH_REDIRECT_IN_STAGE \
        VITE_OAUTH_REDIRECT_OUT_STAGE=$OAUTH_REDIRECT_OUT_STAGE \
        yarn build
      - aws s3 sync dist/ $S3
