version: '3.1'

services:

  htsget:
    image: ga4gh/htsget-refserver:1.5.0
    command: "./htsget-refserver -config /htsget-config-local.json"
    ports:
      - "3100:3100"
    volumes:
      - ./htsget-config-local.json:/htsget-config-local.json
      - ~/.aws:/root/.aws:ro
      - ./vcfs:/vcfs:ro
      - ./bams:/bams:ro
    environment:
      - AWS_PROFILE=dev
