export const AUTH_UPDATE = 'AUTH_UPDATE';

export const SEARCH_QUERY_PARAMS_UPDATED = 'SEARCH_QUERY_PARAMS_UPDATED';
export const SEARCH_QUERY_STARTED_RUNNING = 'SEARCH_QUERY_STARTED_RUNNING';
export const SEARCH_QUERY_SUCCESS = 'SEARCH_QUERY_SUCCESS';
export const SEARCH_QUERY_FAILURE = 'SEARCH_QUERY_FAILURE';
export const SEARCH_QUERY_CLEAR_ERR_MSG = 'SEARCH_QUERY_CLEAR_ERR_MSG';